{
  "masterAddr": "_master_host_",
  "mountPoint": "_dir_/client/mnt",
  "volName": "ltptest",
  "owner": "ltptest",
  "enableRdma": "true",
  "rdmaMemBlockNum": "40960",
  "rdmaMemBlockSize": "131072",
  "rdmaMem1MBlockNum": "10",
  "rdmaMem128KBlockNum": "100",
  "rdmaMemPoolLevel": "18",
  "rdmaHeaderBlockNum": "32768",
  "rdmaHeaderPoolLevel": "15",
  "rdmaResponseBlockNum": "32768",
  "rdmaResponsePoolLevel": "15",
  "wqDepth": "32",
  "minCqeNum": "1024",
  "logDir": "_dir_/client/log",
  "logLevel": "debug"
}
